name: 'Create Ephemeral Heroku Application'
description: 'Create Ephemeral Heroku Application'
inputs:
  DOMAIN:
    description: 'Heroku ephemeral domain'
    required: true
  SUBDOMAIN:
    description: 'subdomain'
    required: true
  HEROKU_API_TOKEN:
    description: 'Heroku api token'
    required: true
  CLOUDFLARE_TOKEN:
    description: 'Cloudflare token'
    required: true
  CLOUDFLARE_ZONE:
    description: 'Cloudflare zone'
    required: true
outputs:
  url:
    description: 'The Heroku application url'
runs:
  using: 'node12'
  main: 'dist/index.js'
